# Reinforcement Learning: Min Distance RL with CARLA CL (Larger Model) 13/01/22

At the recommednation of one of the authors of the paper I will try to adapt the following [tutorial](https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html) to work acheive the same results as in the paper.

Notes: Pygame only runs on python 3.7, pytorch must be install direclty into the env

In [1]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import torchvision.transforms as T

import carla
import math
import random
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
from collections import namedtuple, deque
from itertools import count
from PIL import Image

from torch.utils.tensorboard import SummaryWriter

import gym
import gym_carla

# set up matplotlib
is_ipython = 'inline' in matplotlib.get_backend()
if is_ipython:
    from IPython import display

plt.ion()

# if gpu is to be used
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [2]:
# parameters for the gym_carla environment
params = {
    'number_of_vehicles': 0,
    'number_of_walkers': 0,
    'display_size': 256,  # screen size of bird-eye render
    'max_past_step': 1,  # the number of past steps to draw
    'dt': 0.1,  # time interval between two frames
    'discrete': True,  # whether to use discrete control space
    'discrete_acc': [2.0],  # discrete value of accelerations
    'discrete_steer': [-0.3, 0.0, 0.3],  # discrete value of steering angles
    'continuous_accel_range': [-3.0, 3.0],  # continuous acceleration range
    'continuous_steer_range': [-0.3, 0.3],  # continuous steering angle range
    'ego_vehicle_filter': 'vehicle.lincoln*',  # filter for defining ego vehicle
    'port': 2000,  # connection port
    'town': 'Town04',  # which town to simulate
    'task_mode': 'random',  # mode of the task, [random, roundabout (only for Town03)]
    'max_time_episode': 500,  # maximum timesteps per episode
    'max_waypt': 12,  # maximum number of waypoints
    'obs_range': 32,  # observation range (meter)
    'lidar_bin': 0.125,  # bin size of lidar sensor (meter)
    'd_behind': 12,  # distance behind the ego vehicle (meter)
    'out_lane_thres': 1.8,  # threshold for out of lane
    'desired_speed': 3,  # desired speed (m/s)
    'max_ego_spawn_times': 20,  # maximum times to spawn ego vehicle
    'display_route': True,  # whether to render the desired route
    'pixor_size': 64,  # size of the pixor labels
    'pixor': False,  # whether to output PIXOR observation
    'use_fixed':True,
    'weather':'HardRainSunset',
    'obs_size':128
}

# Set gym-carla environment
env = gym.make('carla-v0', params=params)

pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
connecting to Carla server...
Carla server connected!
WeatherParameters(cloudiness=10.000000, cloudiness=10.000000, precipitation=0.000000, precipitation_deposits=10.000000, wind_intensity=30.000000, sun_azimuth_angle=150.000000, sun_altitude_angle=60.000000, fog_density=40.000000, fog_distance=60.000000, fog_falloff=2.000000, wetness=30.000000, scattering_intensity=1.000000, mie_scattering_scale=0.030000, rayleigh_scattering_scale=0.033100)
372


In [3]:

Transition = namedtuple('Transition',
                        ('state', 'action', 'next_state', 'reward'))

class ReplayMemory(object):

    def __init__(self, capacity):
        self.memory = deque([],maxlen=capacity)

    def push(self, *args):
        """Save a transition"""
        self.memory.append(Transition(*args))

    def sample(self, batch_size):
        return random.sample(self.memory, batch_size)

    
    def __len__(self):
        return len(self.memory)


In [4]:
class PerceptionNet(nn.Module):

    def __init__(self):
        super(PerceptionNet,self).__init__()
        self.conv1 = nn.Conv2d(3, 32, kernel_size=4, stride=2, padding=1)
        
        self.conv2 = nn.Conv2d(32, 64, kernel_size=4, stride=2, padding=1)
        self.bn2 = nn.BatchNorm2d(64)
        
        self.conv3 = nn.Conv2d(64, 128, kernel_size=4, stride=2, padding=1)
        self.bn3 = nn.BatchNorm2d(128)
        
        self.conv4 = nn.Conv2d(128, 256, kernel_size=4, stride=2, padding=1)
        self.bn4 = nn.BatchNorm2d(256)
        
        self.conv5 = nn.Conv2d(256, 512, kernel_size=4, stride=2, padding=1)
        self.bn5 = nn.BatchNorm2d(512)
        
        self.conv6 = nn.Conv2d(512, 64, kernel_size=4, stride=1)
        
        self.conv7 = torch.nn.ConvTranspose2d(64,512, kernel_size =4, stride=1)
        self.bn6 = nn.BatchNorm2d(512)
        
        self.conv8 = torch.nn.ConvTranspose2d(512,256, kernel_size =4, stride=2, padding=1)
        self.bn7 = nn.BatchNorm2d(256)
        
        self.conv9 = torch.nn.ConvTranspose2d(256,128, kernel_size =4, stride=2, padding=1)
        self.bn8 = nn.BatchNorm2d(128)
        
        self.conv10 = torch.nn.ConvTranspose2d(128,64, kernel_size =4, stride=2, padding=1)
        self.bn9 = nn.BatchNorm2d(64)
        
        self.conv11 = torch.nn.ConvTranspose2d(64,32, kernel_size =4, stride=2, padding=1)
        self.bn10 = nn.BatchNorm2d(32)
        
        self.conv12 = torch.nn.ConvTranspose2d(32,23, kernel_size =4, stride=2,padding=1)
        
            
    def encode(self, x):
        x = F.leaky_relu(self.conv1(x),negative_slope=0.02)
        x = F.leaky_relu(self.bn2(self.conv2(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn3(self.conv3(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn4(self.conv4(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn5(self.conv5(x)),negative_slope=0.02)
        return self.conv6(x)
    
    def decode(self, x):
        x = F.leaky_relu(self.bn6(self.conv7(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn7(self.conv8(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn8(self.conv9(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn9(self.conv10(x)),negative_slope=0.02)
        x = F.leaky_relu(self.bn10(self.conv11(x)),negative_slope=0.02)
        return F.log_softmax(self.conv12(x),dim=1)
    
    def forward(self, x):
        x = x.to(device, dtype=torch.float32)
        latent = self.encode(x)
        out = self.decode(latent)
        return out, latent

In [5]:
class Full_DQN(nn.Module):

    def __init__(self, outputs,input_size):
        super(Full_DQN, self).__init__()
        
        self.lin1 = nn.Linear(input_size+9,80)
        self.lin2 = nn.Linear(80,50)
        self.lin3 = nn.Linear(50,25)
        self.lin4 = nn.Linear(25,15)
        self.lin5 = nn.Linear(15,8)
        self.lin6 = nn.Linear(8,3)

    def forward(self, x):
        x = x.to(device)
        x = F.relu(self.lin1(x))
        x = F.relu(self.lin2(x))
        x = F.relu(self.lin3(x))
        x = F.relu(self.lin4(x))
        x = F.relu(self.lin5(x))
        x = self.lin6(x)
        
        return x.view(x.size(0), -1)

In [6]:
BATCH_SIZE = 512
GAMMA = 0.999
EPS_START = 0.9
EPS_END = 0.05
EPS_DECAY = 200000
TARGET_UPDATE = 256

writer = SummaryWriter()

n_actions = env.action_space.n

policy_net = Full_DQN(n_actions,64).to(device)
#policy_net.load_state_dict(torch.load('./model_params_CL/model_10.final'))

target_net = Full_DQN(n_actions,64).to(device)
target_net.load_state_dict(policy_net.state_dict())
target_net.eval()

model = PerceptionNet()
model.to(device)
model.load_state_dict(torch.load('./AE_params/model_3.best'))
model.eval()
for param in model.parameters():
    param.requires_grad = False

# Model <= 7
optimizer = optim.RMSprop(policy_net.parameters(),lr=0.005)

#Model 8 & from 2022 
#optimizer = optim.Adam(policy_net.parameters(),lr=0.005)


memory = ReplayMemory(7500)


steps_done = 0


def select_action(state):
    global steps_done
    sample = random.random()
    eps_threshold = EPS_END + (EPS_START - EPS_END) * \
        math.exp(-1. * steps_done / EPS_DECAY)
    steps_done += 1
    if sample > eps_threshold:
        with torch.no_grad():
            #arg max select the idex of the largest value and view changes shape from (1,) to (1,1)
            #try test net
            return policy_net(state.float()).argmax().view(1,1)
    else:
        return torch.tensor([[random.randrange(n_actions)]], device=device, dtype=torch.long)


episode_durations = []

In [7]:
def optimize_model():
    if len(memory) < BATCH_SIZE:
        return
    transitions = memory.sample(BATCH_SIZE)
    # Transpose the batch (see https://stackoverflow.com/a/19343/3343043 for
    # detailed explanation). This converts batch-array of Transitions
    # to Transition of batch-arrays.
    batch = Transition(*zip(*transitions))

    # Compute a mask of non-final states and concatenate the batch elements
    # (a final state would've been the one after which simulation ended)
    non_final_mask = torch.tensor(tuple(map(lambda s: s is not None,batch.next_state)), device=device, dtype=torch.bool)
    non_final_next_states = torch.cat([s for s in batch.next_state
                                                if s is not None])
    
    state_batch = torch.cat(batch.state)
    action_batch = torch.cat(batch.action)
    reward_batch = torch.cat(batch.reward)
    #reshape state_batch for nn
  
    # Compute Q(s_t, a) - the model computes Q(s_t), then we select the
    # columns of actions taken. These are the actions which would've been taken
    # for each batch state according to policy_net
    
    # selects column of output that was selceted 
    state_action_values = policy_net(torch.reshape(state_batch,(BATCH_SIZE,1,9)).float()).gather(1,action_batch)
    
    
    # Compute V(s_{t+1}) for all next states.
    # Expected values of actions for non_final_next_states are computed based
    # on the "older" target_net; selecting their best reward with max(1)[0].
    # This is merged based on the mask, such that we'll have either the expected
    # state value or 0 in case the state was final.
    next_state_values = torch.zeros(BATCH_SIZE, device=device)
    next_state_values[non_final_mask] = target_net(torch.reshape(non_final_next_states,(list(non_final_next_states.shape)[0]//9,1,9)).float()).max(1)[0].detach()
    # Compute the expected Q values
    expected_state_action_values = (next_state_values * GAMMA) + reward_batch

    # Compute Huber loss
    criterion = nn.SmoothL1Loss()
    loss = criterion(state_action_values, expected_state_action_values.unsqueeze(1))

    # Optimize the model
    optimizer.zero_grad()
    loss.backward()
    for param in policy_net.parameters():
        param.grad.data.clamp(-1, 1)
    optimizer.step()
    
    return loss

In [13]:
num_episodes = 600
use_fixed_idx = 0
env.use_fixed = 'M'
levels = ['E','M','H']
next_lvl = 300
min_overall_loss = 1000
for i_episode in range(num_episodes):
    rewards = []
    # Initialize the environment and state
    obs = env.reset()
    #ego_dir retirves the distance and angle from vehicle to nearest waypoint
    ego_location = env.ego.get_location()
    ego_dir = gym_carla.envs.misc.get_lane_dis(env.waypoints,ego_location.x,ego_location.y)
    #pos gets a distanc d and array w which has to be seperated out in below line
    ego_pos = np.asarray((ego_dir[0],ego_dir[1][0],ego_dir[1][1]),dtype=np.float32)
    state = np.concatenate((ego_pos,np.zeros(6)))
    state = torch.tensor(state)

    
    new_obs = torch.tensor(obs['camera'])
    new_obs = new_obs.permute(2,0,1).reshape(1,3,128,128)
    
    _,latent_space = model(new_obs)
    state = torch.cat((state,latent_space.cpu()),-1)
    latent_space = latent_space.reshape(1,64)
    # Resize, and add a batch dimension (BCHW)
    loss = episode_loss = 1000
    for t in count():
        # Select and perform an action
        action = select_action(state)
        obs, reward, done, info  = env.step(action.item())
        rewards.append(reward)
        reward = torch.tensor([reward], device=device)

        if not done:
            
            #pos gets a distanc d and array w which has to be seperated out in below line
            pos = np.asarray((info['position'][0],info['position'][1][0],info['position'][1][1]))
            ang = np.asarray(info['angular_vel'])
            acc = np.asarray(info['acceleration'])
            steer = np.asarray(info['steer'])
            next_state = np.concatenate((pos, ang, acc, steer), axis=None)
            
            new_obs = torch.tensor(obs['camera'])
            new_obs = new_obs.permute(2,0,1).reshape(1,3,128,128)
            _,latent_space = model(new_obs)
            latent_space = latent_space.reshape(1,64)
            next_state = torch.cat((torch.tensor(next_state),latent_space),1)
        else:
            next_state = None

        memory.push(state, action, next_state, reward)
        
        state = next_state

        # Perform one step of the optimization (on the policy network)
        loss = optimize_model()
        
        #if loss is better than previous minimum save mode
        if loss is not None and loss < episode_loss:
            episode_loss = loss
            writer.add_scalar("Loss/train", loss, i_episode)
        
        if done:
            episode_durations.append(t + 1)
            break
            
    # Update the target network
    if steps_done % TARGET_UPDATE == 0:
        target_net.load_state_dict(policy_net.state_dict())
    len_episode = t+1
    writer.add_scalar("Lenght/Epoch", len_episode, i_episode)
    
    if i_episode > 0 and i_episode % next_lvl == 0:
        #saving model after each level
        torch.save(target_net.state_dict(), './model_params_CL/Full_model_1'+levels[use_fixed_idx]+'.final')
        use_fixed_idx += 1
        env.use_fixed = levels[use_fixed_idx]
    
    #save model if better than previous episode
    if episode_loss < min_overall_loss:
        min_overall_loss = episode_loss
        torch.save(target_net.state_dict(), './model_params_CL/Full_model_1.best')
    

print('Complete')
torch.save(target_net.state_dict(), './model_params_CL/Full_model_1.final')

writer.flush()
writer.close()
env.close()

RuntimeError: Tensors must have same number of dimensions: got 1 and 4

### Visualise Models

In [6]:
target_net.eval()

DQN(
  (lin1): Linear(in_features=9, out_features=80, bias=True)
  (lin2): Linear(in_features=80, out_features=50, bias=True)
  (lin3): Linear(in_features=50, out_features=25, bias=True)
  (lin4): Linear(in_features=25, out_features=15, bias=True)
  (lin5): Linear(in_features=15, out_features=8, bias=True)
  (lin6): Linear(in_features=8, out_features=3, bias=True)
)

In [23]:
torch.save(target_net.state_dict(), './model_params_CL/model_10.final')

In [7]:
vis_net = DQN(n_actions).to(device)
vis_net.load_state_dict(torch.load('./model_params_CL/model_10.final'))
vis_net.eval()



DQN(
  (lin1): Linear(in_features=9, out_features=80, bias=True)
  (lin2): Linear(in_features=80, out_features=50, bias=True)
  (lin3): Linear(in_features=50, out_features=25, bias=True)
  (lin4): Linear(in_features=25, out_features=15, bias=True)
  (lin5): Linear(in_features=15, out_features=8, bias=True)
  (lin6): Linear(in_features=8, out_features=3, bias=True)
)

In [8]:
num_episodes = 8
env.use_fixed = 'H'
env.route_idx = 1
levels = ['E','M','H']
next_lvl = 4
min_overall_loss = 1000
for i_episode in range(num_episodes):
    rewards = 0
    # Initialize the environment and state
    obs = env.reset()
    #ego_dir retirves the distance and angle from vehicle to nearest waypoint
    ego_location = env.ego.get_location()
    ego_dir = gym_carla.envs.misc.get_lane_dis(env.waypoints,ego_location.x,ego_location.y)
    #pos gets a distanc d and array w which has to be seperated out in below line
    ego_pos = np.asarray((ego_dir[0],ego_dir[1][0],ego_dir[1][1]),dtype=np.float32)
    state = np.concatenate((ego_pos,np.zeros(6)))
    state = torch.tensor(state)
    # Resize, and add a batch dimension (BCHW)
    loss = episode_loss = 1000
    for t in count():
        # Select and perform an actionii#
        with torch.no_grad():
            print(state.float())
            action = vis_net(state.float()).argmax().view(1,1)
            print(vis_net(state.float()))
            print(action)
        _ , reward, done, info  = env.step(action.item())
        rewards += reward
        
        #pos gets a distanc d and array w which has to be seperated out in below line
        pos = np.asarray((info['position'][0],info['position'][1][0],info['position'][1][1]))
        ang = np.asarray(info['angular_vel'])
        acc = np.asarray(info['acceleration'])
        steer = np.asarray(info['steer'])
        next_state = np.concatenate((pos, ang, acc, steer), axis=None)
        #update state
        state = torch.tensor(next_state)

        if done:
            print('########')
            episode_durations.append(t + 1)
            break


tensor([0.0035, 1.0000, 0.0057, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000])
tensor([[4.1582],
        [4.1682],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 3.4923e-03,  9.9998e-01,  5.6919e-03, -3.5187e-06, -6.6744e-06,
        -5.2950e-09, -5.2512e-09, -8.2394e-07, -0.0000e+00])
tensor([[4.1582],
        [4.1682],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([3.4923e-03, 9.9998e-01, 5.6919e-03, 4.7972e-05, 6.7963e-06, 7.4775e-10,
        4.1868e-07, 9.2484e-07, -0.0000e+00])
tensor([[4.1582],
        [4.1682],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 3.4923e-03,  9.9998e-01,  5.6919e-03,  5.1451e-06, -6.4934e-06,
        -3.9681e-09, -4.1333e-07, -1.5309e-06, -0.0000e+00])
tensor([[4.1582],
        [4.1682],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 3.4923e-03,  9.9998e-01,  5.6919e-03, -4.7999e-05,  6.2347e-06,
         5.5763e-09,  4.2232e-07, -4.125

tensor([ 3.0257e-01,  9.9998e-01,  5.6919e-03, -4.2522e+00,  1.7389e-01,
        -1.4912e+01,  3.5015e+00, -5.0069e+00, -3.0000e-01])
tensor([[3.9806],
        [3.9568],
        [3.9138]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.3694,  1.0000,  0.0057,  4.9091,  0.5957,  5.5808, -0.4915,  4.1476,
         0.3000])
tensor([[3.8478],
        [3.7965],
        [3.7196]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.8911e-01,  9.9998e-01,  5.6919e-03,  2.3591e+00,  1.5934e+00,
         1.8356e+01, -3.0944e+00,  4.6439e+00,  3.0000e-01])
tensor([[3.7836],
        [3.7190],
        [3.6258]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.8646e-01,  9.9998e-01,  5.6919e-03, -1.8817e-01,  1.3716e+00,
         1.7777e+01, -3.0467e+00,  1.4850e+00,  3.0000e-01])
tensor([[3.9129],
        [3.8751],
        [3.8149]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.7469e-01,  9.9998e-01,  5.6919e-03, -5.5994e-01,  8.4908e-01,
         1.6256

tensor([ 2.3120e-01,  9.9998e-01,  5.6922e-03,  2.1696e+00, -1.4468e+00,
         1.4330e+01,  3.4577e+00,  3.5565e+00,  3.0000e-01])
tensor([[4.0629],
        [4.0562],
        [4.0342]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.8948e-01,  9.9998e-01,  5.6922e-03,  5.5135e-01, -1.6758e+00,
         1.8546e+01,  5.4566e+00,  2.2242e+00,  3.0000e-01])
tensor([[4.1495],
        [4.1627],
        [4.1651]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.5909e-01,  9.9998e-01,  5.6922e-03, -5.7362e+00, -1.8505e+00,
        -3.8480e+00,  7.3132e+00, -4.4068e+00, -3.0000e-01])
tensor([[4.0429],
        [4.0320],
        [4.0049]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([1.3199e-01, 9.9998e-01, 5.6922e-03, 4.1403e+00, 3.0220e-01, 1.3402e+01,
        3.5442e+00, 3.8566e+00, 3.0000e-01])
tensor([[4.1573],
        [4.1686],
        [4.1693]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.0431e-01,  9.9998e-01,  5.6922e-03, -5.1671e+00,  

tensor([ 2.4579e-01,  9.9998e-01,  5.6922e-03,  7.0394e-01, -1.0978e+00,
        -1.3139e+01, -2.1084e+00, -1.4991e+00, -3.0000e-01])
tensor([[4.0756],
        [4.0716],
        [4.0529]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2611,  1.0000,  0.0057,  4.2928, -1.3873,  2.2720, -0.7883,  3.3535,
         0.3000])
tensor([[4.0535],
        [4.0448],
        [4.0204]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.4831e-01,  9.9998e-01,  5.6922e-03,  1.7467e+00, -1.0153e+00,
         1.1295e+01, -4.2892e-01,  2.9146e+00,  3.0000e-01])
tensor([[4.0447],
        [4.0342],
        [4.0076]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.2122e-01,  9.9998e-01,  5.6922e-03,  3.4595e-02, -1.3488e+00,
         1.3000e+01,  1.6602e+00,  1.1514e+00,  3.0000e-01])
tensor([[4.0792],
        [4.0759],
        [4.0581]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.8337e-01,  9.9998e-01,  5.6922e-03,  1.8929e+00, -2.4364e+00,
         1.5770

tensor([ 0.1833,  1.0000,  0.0057,  5.6311,  1.6752,  2.9935, -2.6892,  4.8106,
         0.3000])
tensor([[4.1071],
        [4.1095],
        [4.0989]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1881,  1.0000,  0.0057,  0.1254,  1.3615,  0.1595, -3.0467, -0.0631,
        -0.0000])
tensor([[4.1579],
        [4.1683],
        [4.1684]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.0611e-01,  9.9998e-01,  5.6922e-03, -2.1609e+00,  1.0783e+00,
        -1.0202e+01, -3.3774e+00, -2.5223e+00, -3.0000e-01])
tensor([[4.1021],
        [4.1035],
        [4.0916]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2235,  1.0000,  0.0057,  1.5131,  0.3565, -0.6266, -2.2944,  1.9108,
        -0.0000])
tensor([[4.1272],
        [4.1337],
        [4.1282]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.3199e-01,  9.9998e-01,  5.6922e-03,  1.4441e-01,  1.3478e-02,
        -7.8699e-04, -1.8083e+00,  3.6861e-01, -0.0000e+00])
tensor([[4.1155],
        

tensor([ 1.6090e-01,  9.9998e-01,  5.6919e-03, -3.6714e-01,  9.1658e-01,
        -1.5286e+01, -3.3921e+00, -2.2618e+00, -3.0000e-01])
tensor([[4.0334],
        [4.0725],
        [4.0982]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.9877e-01,  9.9998e-01,  5.6919e-03,  6.4859e-01,  3.0520e-01,
        -1.4010e+01, -2.4882e+00, -4.2303e-01, -3.0000e-01])
tensor([[4.0171],
        [4.0009],
        [3.9673]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2201,  1.0000,  0.0057,  3.7366, -0.1925,  2.2310, -1.5553,  3.6882,
         0.3000])
tensor([[4.1134],
        [4.1172],
        [4.1081]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2284,  1.0000,  0.0057, -0.1688, -0.3551,  0.1855, -0.9976, -0.0371,
        -0.0000])
tensor([[4.0921],
        [4.0914],
        [4.0769]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.2704e-01,  9.9998e-01,  5.6919e-03,  1.7113e+00, -6.2476e-01,
         8.3710e+00, -8.1787e-02,  2.1408e+00,  3.0

tensor([ 1.5502e-01,  9.9998e-01,  5.6919e-03, -3.0570e-01,  1.5797e+00,
        -1.7938e+01, -3.9796e+00, -2.2586e+00, -3.0000e-01])
tensor([[4.0295],
        [4.0704],
        [4.0976]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.0001e-01,  9.9998e-01,  5.6919e-03,  6.7572e-01,  8.3734e-01,
        -1.6363e+01, -3.1376e+00, -5.1883e-01, -3.0000e-01])
tensor([[3.9204],
        [3.9681],
        [3.9992]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.4780e-01,  9.9998e-01,  5.6919e-03,  6.9315e-01,  3.2760e-01,
        -1.4664e+01, -2.6870e+00, -1.2433e-01, -3.0000e-01])
tensor([[3.9427],
        [3.9110],
        [3.8584]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2773,  1.0000,  0.0057,  3.7475, -0.2559,  2.2790, -1.6661,  3.9258,
         0.3000])
tensor([[4.0261],
        [4.0117],
        [3.9804]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.7488e-01,  9.9998e-01,  5.6919e-03,  1.2661e+00, -2.3096e-01,
         1.1347

tensor([ 1.5554e-01,  9.9998e-01,  5.6919e-03,  8.0845e-01, -1.6331e+00,
         2.1249e+01,  6.3058e+00,  2.1579e+00,  3.0000e-01])
tensor([[4.1490],
        [4.1606],
        [4.1619]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.1463e-01,  9.9998e-01,  5.6919e-03, -6.0183e+00, -6.7616e-01,
        -3.6564e+00,  4.8753e+00, -4.9461e+00, -3.0000e-01])
tensor([[4.1584],
        [4.1681],
        [4.1676]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.0947,  1.0000,  0.0057,  0.1827,  1.6625, -0.4511, -1.3639,  0.0506,
        -0.0000])
tensor([[4.1360],
        [4.1481],
        [4.1504]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 9.2441e-02,  9.9998e-01,  5.6919e-03, -2.8695e+00,  2.0691e+00,
        -1.3861e+01, -3.6579e+00, -3.8560e+00, -3.0000e-01])
tensor([[4.1572],
        [4.1685],
        [4.1693]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.2226e-01,  9.9998e-01,  5.6919e-03,  1.7221e-01,  1.7054e+00,
        -1.8473

tensor([ 1.8271e-01,  9.9998e-01,  5.6919e-03,  3.2906e-01, -1.6937e+00,
         1.6678e+01,  4.7319e+00,  1.5575e+00,  3.0000e-01])
tensor([[4.1087],
        [4.1114],
        [4.1012]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 1.4774e-01,  9.9998e-01,  5.6919e-03, -2.8196e+00, -2.1185e+00,
         1.3229e+00,  7.1587e+00, -2.8239e+00, -0.0000e+00])
tensor([[3.9805],
        [4.0399],
        [4.0822]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.4395e-01,  9.9998e-01,  5.6919e-03, -3.9553e+00, -4.0087e-01,
        -1.5477e+01,  4.0966e+00, -4.5135e+00, -3.0000e-01])
tensor([[4.0309],
        [4.0666],
        [4.0902]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.7829e-01,  9.9998e-01,  5.6919e-03, -4.4551e-01,  1.6778e+00,
        -2.1660e+01, -1.9363e+00, -3.2657e+00, -3.0000e-01])
tensor([[3.9287],
        [3.8942],
        [3.8380]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.9755e-01,  9.9998e-01,  5.6919e-03,  6.06

tensor([ 1.4545e-01,  9.9998e-01,  5.6919e-03, -5.3584e-01, -2.7951e-01,
         1.4198e+01, -1.6977e+00,  7.6495e-02,  3.0000e-01])
tensor([[4.1231],
        [4.1288],
        [4.1222]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1158,  1.0000,  0.0057, -2.0232, -0.6853,  2.3128, -0.4051, -2.7590,
        -0.0000])
tensor([[4.1339],
        [4.1419],
        [4.1381]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.0976,  1.0000,  0.0057,  0.0995, -0.7338,  1.1419,  0.3157, -0.4606,
        -0.0000])
tensor([[4.1567],
        [4.1688],
        [4.1701]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 9.0412e-02,  9.9998e-01,  5.6919e-03, -1.8949e+00, -1.1705e+00,
        -8.3909e+00,  1.8733e+00, -2.2987e+00, -3.0000e-01])
tensor([[4.0320],
        [4.0189],
        [3.9890]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.0782,  1.0000,  0.0057,  3.9179, -1.2293,  5.4162,  3.9854,  3.3499,
         0.3000])
tensor([[4.1584],
        

tensor([ 1.5147e+00,  9.9998e-01,  5.6919e-03, -1.1114e-01, -6.4336e-01,
        -2.4352e+01,  2.0721e+00, -2.6043e+00, -3.0000e-01])
tensor([[-9.2488],
        [-8.8653],
        [-8.3958]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.7054e+00,  9.9998e-01,  5.6919e-03, -1.1379e+00,  2.0775e+00,
        -2.4682e+01, -4.7763e-01, -1.4101e+00, -3.0000e-01])
tensor([[-19.5779],
        [-19.4338],
        [-19.1367]], device='cuda:0')
tensor([[2]], device='cuda:0')
########
tensor([2.9122e-06, 9.9987e-01, 1.6127e-02, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00])
tensor([[4.1583],
        [4.1682],
        [4.1678]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-02,  8.9611e-06, -2.2245e-06,
         2.6178e-11, -6.9503e-08, -1.5223e-07, -0.0000e+00])
tensor([[4.1583],
        [4.1682],
        [4.1678]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-

tensor([ 2.3795e-01,  9.9987e-01,  1.6127e-02,  4.5061e-01, -1.5599e+00,
         2.1461e+01,  5.9974e+00,  1.6303e+00,  3.0000e-01])
tensor([[4.1477],
        [4.1614],
        [4.1642]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.2404,  0.9999,  0.0161, -6.2970, -0.0883, -3.5828,  4.3077, -5.4485,
        -0.3000])
tensor([[4.0864],
        [4.0845],
        [4.0686]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2524,  0.9999,  0.0161,  3.7713,  1.5629, 12.2714, -1.6199,  3.3432,
         0.3000])
tensor([[4.1244],
        [4.1391],
        [4.1438]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.2638,  0.9999,  0.0161, -4.3471,  2.1869, -7.6124, -3.6589, -4.0449,
        -0.3000])
tensor([[4.1092],
        [4.1120],
        [4.1019]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2854,  0.9999,  0.0161,  1.0102,  1.4989, -0.3496, -3.5920,  1.2726,
        -0.0000])
tensor([[4.1253],
        [4.1315],
        [4.1255]], device=

tensor([  0.0424,   0.9971,  -0.0758,  -0.8586,  -0.3222, -22.1500,   3.9947,
         -3.4433,  -0.3000])
tensor([[4.0111],
        [4.0514],
        [4.0791]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.0697,   0.9971,  -0.0758,   0.6187,   1.4828, -21.8927,  -1.4888,
         -1.3511,  -0.3000])
tensor([[3.9058],
        [3.9749],
        [4.0275]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.1079,   0.9971,  -0.0758,   0.9381,   1.7898, -20.2999,  -3.2261,
         -0.6434,  -0.3000])
tensor([[3.9820],
        [4.0389],
        [4.0795]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.1530,   0.9971,  -0.0758,   0.9753,   1.4134, -18.1826,  -3.6256,
         -0.1728,  -0.3000])
tensor([[3.8908],
        [3.9651],
        [4.0220]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.2019,   0.9971,  -0.0758,   0.8050,   0.7862, -16.3648,  -3.1445,
          0.0362,  -0.3000])
tensor([[3.8516],
        [3.9219],
        [3.9747]]

tensor([ -0.4020,   0.7712,  -0.6365,   0.3036,   2.0892, -23.4718,  -3.6419,
         -1.7701,  -0.3000])
tensor([[3.9843],
        [4.0514],
        [4.0990]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.3976,   0.7712,  -0.6365,   1.6784,   1.4390, -21.9291,  -3.7314,
          0.8407,  -0.3000])
tensor([[4.0148],
        [4.0724],
        [4.1120]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.3800,   0.7712,  -0.6365,   1.7561,   0.8116, -19.7758,  -3.6289,
          1.6162,  -0.3000])
tensor([[4.0833],
        [4.1255],
        [4.1512]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.3536,   0.7712,  -0.6365,   1.4696,   0.2882, -17.6254,  -3.3015,
          1.9323,  -0.3000])
tensor([[4.0921],
        [4.1304],
        [4.1530]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.3219,   0.7712,  -0.6365,   1.0178,  -0.1462, -15.9474,  -2.6399,
          1.7196,  -0.3000])
tensor([[4.1073],
        [4.1395],
        [4.1571]]

tensor([-4.5344e-01,  1.3464e-02, -9.9991e-01,  8.8216e-01,  3.8507e+00,
        -1.6076e+01, -3.6775e+00,  1.0337e+00, -3.0000e-01])
tensor([[3.9904],
        [4.0473],
        [4.0876]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-4.9473e-01,  1.3464e-02, -9.9991e-01,  1.8345e+00,  1.3944e+00,
        -2.1732e+01, -3.7626e+00,  3.1927e+00, -3.0000e-01])
tensor([[3.9944],
        [4.0463],
        [4.0829]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-5.1516e-01,  1.3464e-02, -9.9991e-01,  1.6195e+00, -1.2350e-03,
        -1.9810e+01, -1.7447e+00,  3.6272e+00, -3.0000e-01])
tensor([[4.1544],
        [4.1666],
        [4.1680]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-5.2246e-01,  1.3464e-02, -9.9991e-01,  1.0836e+00, -3.5649e-01,
        -1.7730e+01, -1.1262e+00,  3.6674e+00, -3.0000e-01])
tensor([[4.1575],
        [4.1684],
        [4.1688]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-5.2068e-01,  1.3464e-02, -9.9991e-01,  4.47

tensor([ 3.7140e-01,  1.3464e-02, -9.9991e-01, -5.6700e-02,  6.2526e-01,
         1.6481e+01,  2.7561e-01,  2.0924e+00,  3.0000e-01])
tensor([[4.1574],
        [4.1685],
        [4.1690]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3296,  0.0135, -0.9999, -0.6277,  4.0615, -2.4614, -4.3220,  0.9986,
        -0.3000])
tensor([[4.1587],
        [4.1679],
        [4.1672]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.3045,  0.0135, -0.9999, -0.2007, -0.4109, -0.1202, -0.0867,  1.2140,
        -0.0000])
tensor([[4.0678],
        [4.0621],
        [4.0414]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2686,  0.0135, -0.9999,  0.0815, -2.4434,  9.3940,  2.2314,  1.3178,
         0.3000])
tensor([[4.1626],
        [4.1709],
        [4.1693]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2326,  0.0135, -0.9999, -0.7021,  1.1003,  0.5361, -1.6681, -0.4143,
        -0.0000])
tensor([[4.1571],
        [4.1686],
        [4.1694]], device=

tensor([ 3.6732e-01,  1.3464e-02, -9.9991e-01,  1.8329e+00,  8.5575e-01,
         1.9656e+01,  9.7296e-01,  3.2583e+00,  3.0000e-01])
tensor([[4.1281],
        [4.1349],
        [4.1296]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.3347,  0.0135, -0.9999,  1.2172,  3.6115,  0.9019, -3.9770,  2.9680,
        -0.0000])
tensor([[4.1577],
        [4.1684],
        [4.1686]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.3329,   0.0135,  -0.9999,   0.8794,   2.8510, -11.5860,  -3.6560,
          3.3063,  -0.3000])
tensor([[4.1072],
        [4.1333],
        [4.1466]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 3.5533e-01,  1.3464e-02, -9.9991e-01,  4.3714e-01, -8.0716e-02,
        -1.5295e+01, -1.8888e+00,  2.8400e+00, -3.0000e-01])
tensor([[4.0265],
        [4.0123],
        [3.9810]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.3652,  0.0135, -0.9999,  0.0873, -3.9107,  0.5907,  3.4192,  1.9034,
         0.3000])
tensor([[4.1111],

tensor([ 3.5746e-01,  1.3464e-02, -9.9991e-01,  1.6674e+00,  1.6583e+00,
        -1.7453e+01, -3.6476e+00,  4.1220e+00, -3.0000e-01])
tensor([[3.8284],
        [3.8996],
        [3.9525]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 4.0012e-01,  1.3464e-02, -9.9991e-01,  8.4893e-01, -5.9916e-01,
        -1.6847e+01, -8.2525e-01,  3.0216e+00, -3.0000e-01])
tensor([[3.9150],
        [3.8777],
        [3.8180]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 4.4599e-01,  1.3464e-02, -9.9991e-01,  3.5725e-01, -8.6202e-01,
        -1.5352e+01, -1.6495e-01,  2.6284e+00, -3.0000e-01])
tensor([[3.7669],
        [3.6989],
        [3.6014]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.4739,  0.0135, -0.9999, -0.3012, -3.9959,  0.4591,  3.7206,  1.8913,
         0.3000])
tensor([[3.7063],
        [3.6257],
        [3.5127]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.4718,  0.0135, -0.9999, -0.4508, -1.2755,  9.2029,  2.8251,  1.9353,
        

tensor([ -1.4767,  -0.3658,  -0.9307,   0.8520,  -0.3137, -16.4061,   0.2846,
          3.1002,  -0.3000])
tensor([[-10.4289],
        [ -9.8049],
        [ -8.6082]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -1.4745,  -0.3658,  -0.9307,   0.3905,  -0.2023, -14.6986,   0.3869,
          2.6419,  -0.3000])
tensor([[-10.9300],
        [-10.3041],
        [ -9.0781]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -1.4667,  -0.3658,  -0.9307,   0.0521,  -0.0393, -13.3410,   0.3467,
          2.0515,  -0.3000])
tensor([[-11.2827],
        [-10.6554],
        [ -9.4088]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -1.4548,  -0.3658,  -0.9307,  -0.1907,   0.1509, -12.4242,   0.1738,
          1.3691,  -0.3000])
tensor([[-11.3611],
        [-10.7335],
        [ -9.4823]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -1.4390,  -0.3658,  -0.9307,   0.0396,   0.7765, -11.9537,  -0.1623,
          0.5485,  -0.3000])
tensor([[-11.0243],
        [

tensor([-0.1930, -0.0135,  0.9999,  0.3634,  2.6256, -0.2026, -2.5567, -0.5914,
        -0.0000])
tensor([[4.1627],
        [4.1663],
        [4.1614]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.1965, -0.0135,  0.9999,  0.5071,  0.4440,  0.9698, -0.4986, -0.1261,
        -0.0000])
tensor([[4.1596],
        [4.1676],
        [4.1659]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.2011, -0.0135,  0.9999,  0.6930,  0.0505,  0.9710, -0.1150,  0.8494,
        -0.0000])
tensor([[4.1600],
        [4.1674],
        [4.1653]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.2064, -0.0135,  0.9999,  0.9265,  0.0058,  0.8900, -0.0883,  2.1064,
        -0.0000])
tensor([[4.1570],
        [4.1659],
        [4.1650]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.2122, -0.0135,  0.9999,  1.1347,  0.0188,  0.7540, -0.1245,  3.4845,
        -0.0000])
tensor([[4.1382],
        [4.1548],
        [4.1602]], device='cuda:0')
tensor([[2]], device='cuda

tensor([ 0.3317, -0.0135,  0.9999,  2.0718,  3.6153,  3.7177, -3.0147,  4.4020,
         0.3000])
tensor([[3.9382],
        [3.9056],
        [3.8518]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.4378e-01, -1.3464e-02,  9.9991e-01,  1.8819e+00,  2.4291e+00,
         1.7446e+01, -3.6681e+00,  5.4509e+00,  3.0000e-01])
tensor([[4.0501],
        [4.0877],
        [4.1118]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3674, -0.0135,  0.9999,  1.0273, -5.7938, -4.0372,  4.9615,  6.5916,
        -0.3000])
tensor([[3.8699],
        [3.9873],
        [4.0752]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 4.4896e-01, -1.3464e-02,  9.9991e-01, -5.6226e-01, -3.7386e+00,
        -2.2569e+01,  6.0970e+00,  2.4827e+00, -3.0000e-01])
tensor([[3.1453],
        [2.9884],
        [2.7839]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.5283, -0.0135,  0.9999, -0.8405,  6.3106,  3.3602, -5.0444, -0.5540,
         0.3000])
tensor([[2.7720],
        

tensor([ 0.3003, -0.0135,  0.9999,  1.5771, -2.4330,  0.0533,  2.6684,  4.2073,
        -0.0000])
tensor([[4.1578],
        [4.1683],
        [4.1684]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.3233,  -0.0135,   0.9999,   1.5375,  -3.6025, -13.2135,   3.9618,
          5.3158,  -0.3000])
tensor([[3.9538],
        [3.9245],
        [3.8747]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.3484, -0.0135,  0.9999,  1.6840,  4.9231,  6.3682, -3.6617,  7.0162,
         0.3000])
tensor([[3.7681],
        [3.7003],
        [3.6031]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.2573e-01, -1.3464e-02,  9.9991e-01, -1.0656e-01,  3.1944e+00,
         2.3425e+01, -5.4074e+00,  3.2233e+00,  3.0000e-01])
tensor([[4.1456],
        [4.1611],
        [4.1653]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3084, -0.0135,  0.9999, -1.7362, -6.3751, -3.5045,  5.1264, -1.2692,
        -0.3000])
tensor([[4.1138],
        [4.1403],
        [4.1537]]

tensor([ 0.3943, -0.1922,  0.9814,  1.8313,  3.7087,  2.0949, -3.1841,  4.3062,
         0.3000])
tensor([[3.6860],
        [3.6012],
        [3.4831]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.4349, -0.1922,  0.9814,  1.7101,  2.6085, 16.4726, -4.0662,  5.3136,
         0.3000])
tensor([[3.6383],
        [3.7431],
        [3.8252]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.4937, -0.1922,  0.9814,  1.3986, -5.6653, -4.0482,  4.5017,  6.9397,
        -0.3000])
tensor([[3.9670],
        [4.0536],
        [4.1157]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.6150,  -0.1922,   0.9814,  -0.3810,  -3.6841, -22.6668,   5.9271,
          2.8851,  -0.3000])
tensor([[ 0.8905],
        [ 0.4113],
        [-0.0862]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.7350, -0.1922,  0.9814, -1.3160,  6.3072,  3.4274, -5.0117, -0.9162,
         0.3000])
tensor([[1.2262],
        [0.8021],
        [0.3576]], device='cuda:0')
tensor([[0]], 

tensor([-4.6109e-02,  9.9998e-01,  5.6919e-03, -3.3508e+00,  4.1672e+00,
        -1.3013e+01, -1.0367e+00, -4.4105e+00, -3.0000e-01])
tensor([[4.1585],
        [4.1680],
        [4.1675]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 1.7165e-03,  9.9998e-01,  5.6919e-03, -2.3490e+00,  4.1057e+00,
        -2.7780e+01, -3.7520e+00, -5.4383e+00, -3.0000e-01])
tensor([[3.9666],
        [3.9399],
        [3.8934]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 4.2047e-02,  9.9998e-01,  5.6919e-03,  7.3121e+00,  3.1286e+00,
         3.3803e+00, -3.8837e+00,  5.6974e+00,  3.0000e-01])
tensor([[4.0514],
        [4.0423],
        [4.0174]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.2353e-02,  9.9998e-01,  5.6919e-03,  3.5728e+00,  2.6401e+00,
         2.2145e+01, -5.7236e+00,  6.0336e+00,  3.0000e-01])
tensor([[4.1533],
        [4.1654],
        [4.1665]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 6.5417e-03,  9.9998e-01,  5.6919e-03, -5.87

tensor([-1.4357e-01,  9.9998e-01,  5.6919e-03,  4.2696e-02,  6.7205e-02,
         4.7031e-04, -6.7222e-02, -3.8466e-03, -0.0000e+00])
tensor([[4.1588],
        [4.1679],
        [4.1671]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-1.7745e-01,  9.9998e-01,  5.6919e-03,  8.8712e-02, -5.8611e-01,
         7.9909e-04,  3.8075e+00,  3.6048e-01, -0.0000e+00])
tensor([[4.1331],
        [4.1546],
        [4.1635]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-1.9217e-01,  9.9998e-01,  5.6919e-03, -3.6132e+00,  7.1171e-01,
        -1.5384e+01, -1.8557e+00, -4.2087e+00, -3.0000e-01])
tensor([[4.1493],
        [4.1603],
        [4.1612]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-1.6899e-01,  9.9998e-01,  5.6919e-03, -4.5122e-01,  1.2453e+00,
        -2.1202e+01, -3.4506e+00, -3.1876e+00, -3.0000e-01])
tensor([[4.1367],
        [4.1552],
        [4.1619]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-1.3087e-01,  9.9998e-01,  5.6919e-03,  8.93

tensor([ 0.2585,  1.0000,  0.0057, -0.1080,  1.5213, -0.1636, -3.3006,  0.0583,
        -0.0000])
tensor([[4.1479],
        [4.1588],
        [4.1586]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.0384,  0.7403,  0.6723,  0.0660,  1.0579, -0.0074, -2.9717, -0.0704,
        -0.0000])
tensor([[4.1602],
        [4.1673],
        [4.1650]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 1.0909e-01,  7.4028e-01,  6.7229e-01,  7.1493e-02,  6.9755e-01,
        -1.4699e-03, -2.4582e+00, -3.0536e-02, -0.0000e+00])
tensor([[4.1585],
        [4.1680],
        [4.1674]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.4279e-01,  7.4028e-01,  6.7229e-01,  5.4254e-02,  4.0137e-01,
        -5.1129e-04, -1.7886e+00, -1.7392e-02, -0.0000e+00])
tensor([[4.1576],
        [4.1684],
        [4.1688]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3742,  0.7403,  0.6723, -1.7360,  0.2398, -8.0236, -1.2380, -2.0540,
        -0.3000])
tensor([[3.9029],
        

tensor([-1.6900e-02, -3.0849e-03,  1.0000e+00,  5.3590e+00,  4.2226e+00,
         1.5388e+01, -4.0433e+00,  2.0851e+01,  3.0000e-01])
tensor([[4.1094],
        [4.1174],
        [4.1180]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-4.1142e-02, -3.0849e-03,  1.0000e+00,  1.2045e+00, -6.6856e+00,
        -5.7654e+00,  3.6061e+00,  1.2138e+01, -3.0000e-01])
tensor([[4.1658],
        [4.1532],
        [4.1368]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([-5.5111e-02, -3.0849e-03,  1.0000e+00, -4.2822e+00,  3.3269e+00,
         4.2653e+00, -2.7705e+00, -6.5801e-01,  3.0000e-01])
tensor([[4.1253],
        [4.1446],
        [4.1524]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-7.1446e-02, -3.0849e-03,  1.0000e+00, -3.8267e+00, -5.2212e+00,
        -9.3086e+00,  3.7388e+00, -3.0281e+00, -3.0000e-01])
tensor([[4.0442],
        [4.0915],
        [4.1226]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-3.4115e-02, -3.0849e-03,  1.0000e+00, -3.62

tensor([ 2.3724e-01, -3.0849e-03,  1.0000e+00, -1.6296e+00,  2.3567e-01,
         1.8850e+01, -2.5387e+00, -4.0901e+00,  3.0000e-01])
tensor([[4.0271],
        [4.0130],
        [3.9819]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.8918e-01, -3.0849e-03,  1.0000e+00, -8.7661e-01, -8.7766e-01,
         1.7192e+01, -5.7244e-01, -3.3119e+00,  3.0000e-01])
tensor([[4.0964],
        [4.0966],
        [4.0832]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 1.5802e-01, -3.0849e-03,  1.0000e+00, -1.9815e-01, -3.0307e+00,
         1.1213e+00,  3.5380e+00, -2.3929e+00, -0.0000e+00])
tensor([[4.1554],
        [4.1667],
        [4.1675]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.5348e-01, -3.0849e-03,  1.0000e+00, -6.6774e-02, -2.3436e+00,
        -9.2124e+00,  3.1154e+00, -2.5372e+00, -3.0000e-01])
tensor([[4.1579],
        [4.1682],
        [4.1683]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.7017e-01, -3.0849e-03,  1.0000e+00,  1.86

tensor([ 1.1248e-01, -3.0849e-03,  1.0000e+00,  1.5451e+00, -7.8416e-02,
        -1.8788e-02,  1.1585e-01,  6.9561e+00, -0.0000e+00])
tensor([[4.1608],
        [4.1671],
        [4.1642]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 1.2014e-01, -3.0849e-03,  1.0000e+00,  7.2607e-03, -3.6666e-02,
        -1.2183e-02,  6.7883e-02,  4.0806e+00, -0.0000e+00])
tensor([[4.1548],
        [4.1635],
        [4.1626]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1279, -0.0031,  1.0000, -1.8821, -0.0095, -0.4776, -0.0255, -1.6454,
        -0.0000])
tensor([[4.1578],
        [4.1683],
        [4.1684]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.5337e-01, -3.0849e-03,  1.0000e+00, -2.4717e+00, -3.4102e+00,
        -1.5669e+01,  3.7834e+00, -4.2710e+00, -3.0000e-01])
tensor([[4.1423],
        [4.1591],
        [4.1643]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.0986e-01, -3.0849e-03,  1.0000e+00, -1.7984e+00, -2.0978e-01,
        -2.0921

tensor([ 1.4136, -0.7163,  0.6978,  0.7937,  1.1254, 14.2517, -2.3253,  2.0203,
         0.3000])
tensor([[-11.1882],
        [-11.7168],
        [-12.1858]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.4326, -0.7163,  0.6978,  0.8927,  1.5286, 17.1605, -3.8608,  3.3533,
         0.3000])
tensor([[-11.5046],
        [-12.1451],
        [-12.7286]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.4476, -0.7163,  0.6978,  0.8013,  1.7137, 21.0815, -5.1969,  4.0967,
         0.3000])
tensor([[-12.6379],
        [-13.4124],
        [-14.1274]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.4535, -0.7163,  0.6978, -0.1624,  0.5547, 23.8190, -3.9039,  1.9362,
         0.3000])
tensor([[-14.3667],
        [-14.6889],
        [-14.9183]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.4453e+00, -7.1632e-01,  6.9777e-01, -1.1771e+00, -1.2146e+00,
         2.3274e+01, -1.4718e-02, -2.0992e+00,  3.0000e-01])
tensor([[-12.1537],
        [-12.4760]

tensor([ 7.4539e-03, -8.9173e-03,  9.9996e-01, -4.5009e-01, -2.2298e+00,
        -1.0428e+01,  2.4416e+00, -3.6773e+00, -3.0000e-01])
tensor([[4.1581],
        [4.1681],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.0282, -0.0089,  1.0000,  0.1740,  1.4758, -0.6418, -1.9917, -2.4385,
        -0.0000])
tensor([[4.1589],
        [4.1679],
        [4.1670]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 3.9414e-02, -8.9173e-03,  9.9996e-01,  3.4192e-01,  8.4050e-02,
        -1.0118e-03, -4.0211e-01, -1.9552e+00, -0.0000e+00])
tensor([[4.1578],
        [4.1683],
        [4.1684]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.0590, -0.0089,  1.0000,  0.3366, -1.8030, -8.0247,  1.9200, -1.5562,
        -0.3000])
tensor([[4.1586],
        [4.1679],
        [4.1673]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 9.5183e-02, -8.9173e-03,  9.9996e-01,  6.1301e-01, -6.1573e-02,
        -1.1356e+01,  1.3536e+00, -7.2961e-01, -3.0

tensor([-2.2498e-02, -8.9173e-03,  9.9996e-01, -1.3304e+00, -1.2773e-01,
        -3.9166e-04,  8.2549e-02, -1.0478e+00, -0.0000e+00])
tensor([[4.1589],
        [4.1678],
        [4.1669]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-4.4515e-02, -8.9173e-03,  9.9996e-01, -1.7580e+00, -1.5322e-01,
        -8.0500e-04,  2.2648e-01, -2.9047e+00, -0.0000e+00])
tensor([[4.1580],
        [4.1682],
        [4.1681]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-6.4288e-02, -8.9173e-03,  9.9996e-01, -1.4639e+00, -1.2493e-01,
        -9.1482e-04,  2.6483e-01, -3.4017e+00, -0.0000e+00])
tensor([[4.1576],
        [4.1684],
        [4.1688]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-6.8668e-02, -8.9173e-03,  9.9996e-01, -8.6897e-01, -2.6645e+00,
        -1.0827e+01,  3.0256e+00, -3.2771e+00, -3.0000e-01])
tensor([[4.1586],
        [4.1679],
        [4.1673]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.0710, -0.0089,  1.0000, -0.4624,  1.5679,

tensor([-1.3523e-01, -8.9173e-03,  9.9996e-01,  1.4046e+00, -1.0250e-01,
         9.1061e-04,  1.5317e-01,  3.5919e+00, -0.0000e+00])
tensor([[4.1460],
        [4.1589],
        [4.1614]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-1.0686e-01, -8.9173e-03,  9.9996e-01,  1.1956e+00, -3.3837e+00,
        -1.2846e+01,  3.5044e+00,  4.4223e+00, -3.0000e-01])
tensor([[4.1623],
        [4.1665],
        [4.1621]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.0720, -0.0089,  1.0000,  1.7434,  1.8585, -0.8249, -1.8007,  6.9164,
        -0.0000])
tensor([[4.1605],
        [4.1673],
        [4.1647]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.0434, -0.0089,  1.0000,  0.1680,  0.2518,  0.1008, -0.1370,  4.1620,
        -0.0000])
tensor([[4.1613],
        [4.1668],
        [4.1634]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-0.0153, -0.0089,  1.0000, -1.7494,  0.0904,  0.5387, -0.1662, -1.5889,
        -0.0000])
tensor([[4.1587],
        

tensor([ 1.2435e-01, -8.9173e-03,  9.9996e-01, -1.1005e+00,  4.7231e-01,
        -1.9794e+01,  1.9889e+00, -3.1749e+00, -3.0000e-01])
tensor([[4.1582],
        [4.1682],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1190, -0.0089,  1.0000, -1.0213,  3.5473, -1.7094, -3.3528, -3.3512,
        -0.0000])
tensor([[4.1583],
        [4.1682],
        [4.1679]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1000, -0.0089,  1.0000, -0.1667,  0.5467, -0.1271, -0.5474, -2.1726,
        -0.0000])
tensor([[4.1572],
        [4.1685],
        [4.1693]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 9.3508e-02, -8.9173e-03,  9.9996e-01,  1.6657e-01, -2.3562e+00,
        -1.0427e+01,  2.6881e+00, -1.8928e+00, -3.0000e-01])
tensor([[4.1584],
        [4.1680],
        [4.1675]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.0884, -0.0089,  1.0000,  0.1877,  1.5171, -0.7240, -1.7930, -1.2826,
        -0.0000])
tensor([[4.1577],
        

tensor([ 0.5046, -0.0089,  1.0000, -0.8946,  6.0129,  3.4803, -4.8900, -0.6151,
         0.3000])
tensor([[2.9445],
        [2.7616],
        [2.5261]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 5.1855e-01, -8.9173e-03,  9.9996e-01, -1.8543e+00,  2.7888e+00,
         1.8885e+01, -5.2960e+00, -3.5050e+00,  3.0000e-01])
tensor([[3.5294],
        [3.4220],
        [3.2768]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 5.0645e-01, -8.9173e-03,  9.9996e-01, -1.6108e+00, -5.3442e-01,
         1.8405e+01, -1.6618e+00, -3.5888e+00,  3.0000e-01])
tensor([[3.7524],
        [3.6814],
        [3.5801]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 4.8471e-01, -8.9173e-03,  9.9996e-01, -9.6849e-01, -1.0756e+00,
         1.6725e+01, -6.7930e-01, -3.1979e+00,  3.0000e-01])
tensor([[3.8060],
        [3.7460],
        [3.6585]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 4.5761e-01, -8.9173e-03,  9.9996e-01, -4.4984e-01, -1.0344e+00,
         1.5195

tensor([ 6.4572e-02, -8.9173e-03,  9.9996e-01,  1.5317e+00, -7.8661e-02,
         1.1347e-03,  6.0512e-03,  5.1735e+00, -0.0000e+00])
tensor([[4.1600],
        [4.1674],
        [4.1652]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 6.7791e-02, -8.9173e-03,  9.9996e-01,  1.5602e+00, -5.4443e-02,
         1.6586e-03,  6.9498e-03,  6.6999e+00, -0.0000e+00])
tensor([[4.1610],
        [4.1670],
        [4.1640]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 7.1461e-02, -8.9173e-03,  9.9996e-01,  9.6735e-02, -3.6455e-02,
         9.8498e-04,  4.4999e-03,  4.1307e+00, -0.0000e+00])
tensor([[4.1582],
        [4.1653],
        [4.1630]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 7.5216e-02, -8.9173e-03,  9.9996e-01, -1.8098e+00, -2.3655e-02,
        -6.3377e-04,  1.1343e-04, -1.6234e+00, -0.0000e+00])
tensor([[4.1581],
        [4.1681],
        [4.1680]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 7.8673e-02, -8.9173e-03,  9.9996e-01, -2.13

tensor([ 0.1912, -0.0089,  1.0000, -1.6875, -1.8940, -8.8657,  1.3386, -1.9691,
        -0.3000])
tensor([[4.1574],
        [4.1684],
        [4.1689]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.2238e-01, -8.9173e-03,  9.9996e-01, -9.6490e-01, -1.2353e-01,
        -1.1712e+01,  1.1407e+00, -9.3868e-01, -3.0000e-01])
tensor([[4.1577],
        [4.1683],
        [4.1685]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.5874e-01, -8.9173e-03,  9.9996e-01, -2.8991e-01,  4.0895e-01,
        -1.1987e+01,  4.9866e-01,  3.7984e-01, -3.0000e-01])
tensor([[4.1372],
        [4.1459],
        [4.1429]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2854, -0.0089,  1.0000,  0.6152,  1.2847, -1.8384, -2.2321,  2.0626,
        -0.0000])
tensor([[3.9776],
        [3.9533],
        [3.9096]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2927, -0.0089,  1.0000,  1.5491,  2.1749,  8.9100, -2.6753,  3.5507,
         0.3000])
tensor([[4.1344],
        

tensor([ 0.2114, -0.0089,  1.0000, -0.5273, -2.7482,  0.7638,  2.2272, -0.3057,
        -0.0000])
tensor([[4.1548],
        [4.1655],
        [4.1659]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.2176, -0.0089,  1.0000, -1.5735, -2.5027, -8.0713,  2.5082,  0.9524,
        -0.3000])
tensor([[4.1356],
        [4.1556],
        [4.1634]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.4562e-01, -8.9173e-03,  9.9996e-01,  3.0107e-01, -1.3286e+00,
        -1.4149e+01,  2.1719e+00,  3.3657e+00, -3.0000e-01])
tensor([[4.1496],
        [4.1609],
        [4.1611]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.8887e-01, -8.9173e-03,  9.9996e-01,  2.1745e-01, -4.5135e-01,
        -1.7623e+01,  1.6452e+00,  4.6842e+00, -3.0000e-01])
tensor([[4.0949],
        [4.0948],
        [4.0810]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.3200, -0.0089,  1.0000,  0.4764,  5.6841,  3.8030, -4.3326,  6.8841,
         0.3000])
tensor([[4.0238],
        

tensor([ 2.9039e-01, -8.9173e-03,  9.9996e-01, -8.5853e-02, -1.1354e+00,
         1.3664e+01, -2.6534e-01, -2.3916e+00,  3.0000e-01])
tensor([[3.9786],
        [3.9544],
        [3.9109]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.6171e-01, -8.9173e-03,  9.9996e-01,  2.3372e-01, -9.0812e-01,
         1.2408e+01, -1.3724e-01, -1.6965e+00,  3.0000e-01])
tensor([[4.0494],
        [4.0398],
        [4.0144]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.3060e-01, -8.9173e-03,  9.9996e-01,  4.8131e-01, -6.1159e-01,
         1.1391e+01, -1.9440e-01, -9.1658e-01,  3.0000e-01])
tensor([[4.1326],
        [4.1403],
        [4.1361]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2114, -0.0089,  1.0000,  0.8878, -1.8238,  0.6289,  2.3893,  0.6433,
        -0.0000])
tensor([[4.1504],
        [4.1618],
        [4.1622]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.1261e-01, -8.9173e-03,  9.9996e-01,  1.1855e+00, -1.9580e+00,
        -8.9638

tensor([ 0.1444, -0.0089,  1.0000,  0.1714, -1.6932, -7.7419,  1.8732, -1.6178,
        -0.3000])
tensor([[4.1577],
        [4.1683],
        [4.1685]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.7054e-01, -8.9173e-03,  9.9996e-01,  5.7990e-01, -9.9240e-02,
        -1.0955e+01,  1.3532e+00, -4.9366e-01, -3.0000e-01])
tensor([[4.1577],
        [4.1683],
        [4.1686]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.0365e-01, -8.9173e-03,  9.9996e-01,  1.0297e+00,  1.6591e-01,
        -1.1928e+01,  7.3469e-01,  1.2719e+00, -3.0000e-01])
tensor([[4.1586],
        [4.1680],
        [4.1673]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.2273, -0.0089,  1.0000,  2.0171,  2.0063, -0.7516, -2.3293,  4.6921,
        -0.0000])
tensor([[4.1110],
        [4.1343],
        [4.1455]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.5694e-01, -8.9173e-03,  9.9996e-01,  1.3400e+00, -3.1643e+00,
        -1.2326e+01,  2.9782e+00,  4.6137e+00, -3.0

tensor([-1.0833e-01, -8.9173e-03,  9.9996e-01, -6.1153e-01, -4.5071e-02,
        -1.4795e-04,  6.3683e-02, -7.8382e-01, -0.0000e+00])
tensor([[4.1593],
        [4.1677],
        [4.1663]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-1.3402e-01, -8.9173e-03,  9.9996e-01, -3.5586e-01, -2.5781e-02,
        -1.4769e-04,  6.4250e-02, -7.8962e-01, -0.0000e+00])
tensor([[4.1594],
        [4.1676],
        [4.1662]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([-1.6098e-01, -8.9173e-03,  9.9996e-01,  1.0418e+00,  8.7287e-02,
         9.6576e-04, -3.0817e-01,  3.7764e+00, -0.0000e+00])
tensor([[4.1502],
        [4.1611],
        [4.1619]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-1.6938e-01, -8.9173e-03,  9.9996e-01, -4.0196e-01, -3.8331e+00,
        -1.5627e+01,  4.2716e+00, -8.7406e-01, -3.0000e-01])
tensor([[4.1153],
        [4.1397],
        [4.1515]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-1.3956e-01, -8.9173e-03,  9.9996e-01, -1.16

tensor([ 3.5455e-01, -8.9173e-03,  9.9996e-01,  2.9730e-01,  4.4795e+00,
         1.6637e+01, -4.3391e+00,  3.9362e+00,  3.0000e-01])
tensor([[4.1263],
        [4.1488],
        [4.1588]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3870, -0.0089,  1.0000, -2.8057, -5.3549, -6.1560,  4.2538, -2.0689,
        -0.3000])
tensor([[3.5525],
        [3.7002],
        [3.8239]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 4.6390e-01, -8.9173e-03,  9.9996e-01, -2.6568e+00, -2.1355e+00,
        -2.0555e+01,  4.2242e+00, -4.9163e+00, -3.0000e-01])
tensor([[2.9366],
        [2.7526],
        [2.5159]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.5278, -0.0089,  1.0000, -0.8789,  5.5399,  3.7740, -5.0603, -2.9857,
         0.3000])
tensor([[3.1230],
        [2.9631],
        [2.7551]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 5.4359e-01, -8.9173e-03,  9.9996e-01, -9.5049e-01,  2.1827e+00,
         1.7012e+01, -4.5533e+00, -3.9459e+00,  3.0

tensor([ 2.2132e-01, -8.9173e-03,  9.9996e-01,  5.8232e-01, -3.8311e-02,
         1.3476e+01, -4.4463e-01,  2.1533e-01,  3.0000e-01])
tensor([[4.1304],
        [4.1377],
        [4.1330]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1919, -0.0089,  1.0000,  1.1320, -1.8387,  1.8404,  2.3874,  2.5661,
        -0.0000])
tensor([[4.1407],
        [4.1580],
        [4.1637]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.8408e-01, -8.9173e-03,  9.9996e-01,  1.4699e+00, -2.6191e+00,
        -1.0304e+01,  2.9716e+00,  4.1460e+00, -3.0000e-01])
tensor([[4.1586],
        [4.1680],
        [4.1673]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1753, -0.0089,  1.0000,  1.3667,  2.0966, -0.2674, -2.4241,  6.1029,
        -0.0000])
tensor([[4.1568],
        [4.1688],
        [4.1700]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.7174e-01, -8.9173e-03,  9.9996e-01,  3.1933e-01, -3.2386e+00,
        -1.4745e+01,  3.2928e+00,  4.5012e+00, -3.0

tensor([-4.2935e-02,  9.9998e-01,  5.6919e-03, -3.3516e+00,  4.1666e+00,
        -1.3015e+01, -1.0355e+00, -4.4108e+00, -3.0000e-01])
tensor([[4.1584],
        [4.1680],
        [4.1676]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 4.8443e-03,  9.9998e-01,  5.6919e-03, -2.3495e+00,  4.1056e+00,
        -2.7780e+01, -3.7515e+00, -5.4388e+00, -3.0000e-01])
tensor([[3.9644],
        [3.9373],
        [3.8902]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.0491,  1.0000,  0.0057,  4.6001,  3.1274, -3.0261, -3.7098,  4.1383,
        -0.0000])
tensor([[4.1593],
        [4.1677],
        [4.1663]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.0712,  1.0000,  0.0057,  0.9826,  2.4389, -0.0841, -4.7700,  1.1542,
        -0.0000])
tensor([[4.1234],
        [4.1491],
        [4.1615]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.0703e-01,  9.9998e-01,  5.6919e-03, -3.0684e+00,  1.9088e+00,
        -1.5238e+01, -5.2602e+00, -3.3654e+00, -3.0

tensor([ 2.5781e-01,  9.9998e-01,  5.6919e-03,  3.2477e-01, -8.6638e-01,
         1.2217e+01,  7.1700e-01,  1.5865e+00,  3.0000e-01])
tensor([[4.0249],
        [4.0103],
        [3.9787]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.2972e-01,  9.9998e-01,  5.6919e-03,  1.6335e-01, -1.3765e+00,
         1.4120e+01,  2.9273e+00,  1.0307e+00,  3.0000e-01])
tensor([[4.0898],
        [4.0886],
        [4.0735]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.8980e-01,  9.9998e-01,  5.6919e-03,  5.0191e-01, -1.6681e+00,
         1.7065e+01,  4.9264e+00,  1.5235e+00,  3.0000e-01])
tensor([[4.1021],
        [4.1035],
        [4.0916]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 1.5942e-01,  9.9998e-01,  5.6919e-03, -2.9372e+00, -2.0385e+00,
         1.2820e+00,  7.4119e+00, -3.0704e+00, -0.0000e+00])
tensor([[3.9129],
        [3.9856],
        [4.0404]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.6212e-01,  9.9998e-01,  5.6919e-03, -4.08

tensor([ 5.6187e-02,  9.9998e-01,  5.6922e-03, -2.2842e+00,  9.2429e-03,
        -9.9802e+00, -2.4178e+00, -3.0732e+00, -3.0000e-01])
tensor([[4.1435],
        [4.1601],
        [4.1651]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 7.1774e-02,  9.9998e-01,  5.6922e-03,  1.1794e-01, -2.1388e-01,
        -1.3436e+01, -1.7122e+00, -1.6217e+00, -3.0000e-01])
tensor([[4.1323],
        [4.1400],
        [4.1358]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 9.3431e-02,  9.9998e-01,  5.6922e-03,  6.6411e-01, -4.2343e-01,
        -1.3090e+01, -8.6027e-01, -4.4709e-01, -3.0000e-01])
tensor([[4.0989],
        [4.1237],
        [4.1365]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.1867e-01,  9.9998e-01,  5.6922e-03,  4.8596e-01, -5.6392e-01,
        -1.2865e+01, -2.4386e-01, -3.3763e-01, -3.0000e-01])
tensor([[4.0504],
        [4.0478],
        [4.0299]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.1303,  1.0000,  0.0057,  3.3409, -0.8459,

tensor([ 2.8097e-01,  9.9998e-01,  5.6922e-03, -1.2361e-01, -5.4792e-01,
         1.5092e+01,  6.3641e-02,  4.9279e-01,  3.0000e-01])
tensor([[4.0379],
        [4.0260],
        [3.9976]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.2767e-01,  9.9998e-01,  5.6922e-03,  1.7254e-01, -7.6943e-01,
         1.5652e+01,  8.9463e-01,  7.8084e-01,  3.0000e-01])
tensor([[4.0778],
        [4.0742],
        [4.0560]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.6470e-01,  9.9998e-01,  5.6922e-03,  4.0145e-01, -8.7657e-01,
         1.6790e+01,  1.8325e+00,  1.1694e+00,  3.0000e-01])
tensor([[4.1206],
        [4.1259],
        [4.1187]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1104,  1.0000,  0.0057, -2.2997, -1.4480,  2.0192,  3.8887, -2.6291,
        -0.0000])
tensor([[4.0619],
        [4.0911],
        [4.1086]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 8.1350e-02,  9.9998e-01,  5.6922e-03, -3.2053e+00, -1.2937e+00,
        -1.2887

tensor([ 2.0417e-01,  9.9998e-01,  5.6919e-03, -3.4787e+00,  2.1550e+00,
        -8.6778e+00, -3.5964e+00, -3.1269e+00, -3.0000e-01])
tensor([[4.1563],
        [4.1685],
        [4.1699]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.4740e-01,  9.9998e-01,  5.6919e-03, -1.0360e+00,  1.7064e+00,
        -1.7746e+01, -4.3351e+00, -3.0933e+00, -3.0000e-01])
tensor([[3.9739],
        [3.9488],
        [3.9041]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.2770,  1.0000,  0.0057,  4.7329,  0.6730,  3.3858, -2.8317,  4.3927,
         0.3000])
tensor([[4.0207],
        [4.0053],
        [3.9726]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.6835e-01,  9.9998e-01,  5.6919e-03,  1.7116e+00,  4.9730e-01,
         1.4817e+01, -3.3080e+00,  3.5847e+00,  3.0000e-01])
tensor([[4.0505],
        [4.0412],
        [4.0161]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.4456e-01,  9.9998e-01,  5.6919e-03, -6.0637e-01,  1.8926e-02,
         1.4666

tensor([ 4.6010e-02,  9.9998e-01,  5.6919e-03, -3.9604e+00, -4.6312e-01,
        -1.5718e+01,  4.2309e+00, -4.2048e+00, -3.0000e-01])
tensor([[4.1323],
        [4.1473],
        [4.1518]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 7.4602e-02,  9.9998e-01,  5.6919e-03, -6.3096e-01,  1.6789e+00,
        -2.1982e+01, -1.8737e+00, -3.3189e+00, -3.0000e-01])
tensor([[4.0232],
        [4.0083],
        [3.9762]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 8.8457e-02,  9.9998e-01,  5.6919e-03,  6.0024e+00,  2.0455e+00,
         3.7835e+00, -3.1654e+00,  5.0535e+00,  3.0000e-01])
tensor([[4.1534],
        [4.1655],
        [4.1666]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 9.3390e-02,  9.9998e-01,  5.6919e-03, -2.7463e+00,  1.6403e+00,
        -8.9358e+00, -3.8991e+00, -2.6822e+00, -3.0000e-01])
tensor([[4.1573],
        [4.1685],
        [4.1692]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.2724e-01,  9.9998e-01,  5.6919e-03, -5.86

tensor([ 1.0154e-01,  9.9998e-01,  5.6919e-03,  2.6893e+00, -1.6177e+00,
         1.2306e+01,  4.7480e+00,  2.9961e+00,  3.0000e-01])
tensor([[4.1578],
        [4.1683],
        [4.1685]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 9.7672e-02,  9.9998e-01,  5.6919e-03, -4.7970e+00, -1.7799e+00,
        -6.0730e+00,  6.7797e+00, -3.7806e+00, -3.0000e-01])
tensor([[4.0562],
        [4.0480],
        [4.0244]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 9.6848e-02,  9.9998e-01,  5.6919e-03,  3.9592e+00, -2.4608e-01,
         1.1151e+01,  4.2374e+00,  3.6581e+00,  3.0000e-01])
tensor([[4.1591],
        [4.1678],
        [4.1667]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 5.3701e-02,  9.9998e-01,  5.6919e-03,  1.3097e+00,  1.7888e+00,
         2.2626e+01, -2.2038e+00,  3.9351e+00,  3.0000e-01])
tensor([[4.1588],
        [4.1679],
        [4.1670]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.0203,  1.0000,  0.0057, -3.7094,  1.6984,

tensor([ 1.4212e-01,  9.9998e-01,  5.6919e-03, -1.9169e+00,  6.1209e-01,
        -1.7796e+01, -8.2933e-01, -4.1529e+00, -3.0000e-01])
tensor([[4.0193],
        [4.0036],
        [3.9705]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.1551,  1.0000,  0.0057,  5.0872,  0.3649,  3.7161, -0.0063,  4.3376,
         0.3000])
tensor([[4.1583],
        [4.1682],
        [4.1679]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1521,  1.0000,  0.0057, -0.0705,  0.1557,  0.1294, -0.0477, -0.3287,
        -0.0000])
tensor([[4.1573],
        [4.1686],
        [4.1694]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.6587e-01,  9.9998e-01,  5.6919e-03, -2.6935e+00,  7.3905e-01,
        -1.2119e+01, -1.3290e+00, -3.1626e+00, -3.0000e-01])
tensor([[4.1092],
        [4.1121],
        [4.1020]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1801,  1.0000,  0.0057,  1.7557,  1.0133, -0.7303, -3.4798,  2.1915,
        -0.0000])
tensor([[4.0920],
        

tensor([ 0.1439,  1.0000,  0.0057, -2.1853, -1.8313,  0.7334,  4.8457, -2.5341,
        -0.0000])
tensor([[4.0376],
        [4.0725],
        [4.0952]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.4557e-01,  9.9998e-01,  5.6919e-03, -3.4555e+00, -1.8554e+00,
        -1.3492e+01,  6.0116e+00, -3.7474e+00, -3.0000e-01])
tensor([[4.0230],
        [4.0596],
        [4.0842]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.8310e-01,  9.9998e-01,  5.6919e-03, -7.1065e-01, -3.7568e-01,
        -2.1730e+01,  4.0063e+00, -3.3761e+00, -3.0000e-01])
tensor([[3.9948],
        [4.0400],
        [4.0718]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.3761e-01,  9.9998e-01,  5.6919e-03,  7.4234e-01,  1.4355e+00,
        -2.1614e+01, -1.4452e+00, -1.3264e+00, -3.0000e-01])
tensor([[3.9039],
        [3.8642],
        [3.8017]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 2.7192e-01,  9.9998e-01,  5.6919e-03,  5.9601e+00,  1.5471e+00,
         3.0301

tensor([ 1.4590e-01,  9.9998e-01,  5.6919e-03,  2.4463e+00, -1.4901e+00,
         8.8861e+00,  2.4098e+00,  2.4463e+00,  3.0000e-01])
tensor([[4.0906],
        [4.0896],
        [4.0747]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.0975e-01,  9.9998e-01,  5.6919e-03,  2.0025e+00, -3.6492e+00,
         1.5802e+01,  4.7273e+00,  2.6281e+00,  3.0000e-01])
tensor([[4.1157],
        [4.1270],
        [4.1261]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 7.9371e-02,  9.9998e-01,  5.6919e-03, -3.4850e+00, -6.5783e+00,
         1.1941e+00,  7.1597e+00, -2.6179e+00, -0.0000e+00])
tensor([[4.0696],
        [4.1100],
        [4.1351]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 6.0189e-02,  9.9998e-01,  5.6919e-03, -3.8541e-01, -7.4146e+00,
         1.2160e-01,  6.5457e+00, -3.3235e-01, -0.0000e+00])
tensor([[4.0552],
        [4.1021],
        [4.1323]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 6.0301e-02,  9.9998e-01,  5.6919e-03, -4.01

tensor([ 3.4434e-01,  9.9998e-01,  5.6919e-03,  3.1110e+00, -3.4681e+00,
         1.6392e+01,  4.3846e+00,  3.7356e+00,  3.0000e-01])
tensor([[4.0804],
        [4.0774],
        [4.0599]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.1720e-01,  9.9998e-01,  5.6919e-03,  4.9224e-01, -7.1184e+00,
         2.1061e+01,  5.6625e+00,  2.0664e+00,  3.0000e-01])
tensor([[4.0928],
        [4.1220],
        [4.1382]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.7126e-01,  9.9998e-01,  5.6919e-03, -3.0712e-01, -9.0256e+00,
         2.4822e+01,  5.7166e+00,  2.4027e+00,  3.0000e-01])
tensor([[4.0009],
        [4.0600],
        [4.1012]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.3905e-01,  9.9998e-01,  5.6919e-03, -6.4198e+00, -8.4924e+00,
        -2.8646e+00,  3.8973e+00, -5.4976e+00, -3.0000e-01])
tensor([[2.7290],
        [2.7494],
        [2.8220]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 2.6606e-01,  9.9998e-01,  5.6919e-03, -1.04

tensor([-2.9970e-01,  9.9998e-01,  5.6919e-03, -1.9094e-01,  9.9764e-01,
        -1.7467e+01, -3.2890e+00, -2.3938e+00, -3.0000e-01])
tensor([[4.1187],
        [4.1433],
        [4.1552]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-2.8653e-01,  9.9998e-01,  5.6919e-03,  7.2013e-01,  4.7316e-01,
        -1.6102e+01, -2.6757e+00, -7.3109e-01, -3.0000e-01])
tensor([[4.1253],
        [4.1474],
        [4.1572]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-2.6818e-01,  9.9998e-01,  5.6919e-03,  7.0446e-01,  5.8149e-02,
        -1.4818e+01, -2.1002e+00, -3.8260e-01, -3.0000e-01])
tensor([[4.1333],
        [4.1523],
        [4.1595]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-2.4620e-01,  9.9998e-01,  5.6919e-03,  5.1038e-01, -2.4760e-01,
        -1.3916e+01, -1.4099e+00, -2.8582e-01, -3.0000e-01])
tensor([[4.1399],
        [4.1565],
        [4.1617]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-2.2088e-01,  9.9998e-01,  5.6919e-03,  2.73

tensor([ 7.7445e-02,  9.9998e-01,  5.6919e-03, -3.6939e+00, -4.8742e-01,
        -1.5799e+01,  4.4674e+00, -4.0569e+00, -3.0000e-01])
tensor([[4.0842],
        [4.1096],
        [4.1235]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.0166e-01,  9.9998e-01,  5.6919e-03, -4.9809e-01,  1.6733e+00,
        -2.2731e+01, -1.7117e+00, -3.2316e+00, -3.0000e-01])
tensor([[3.9800],
        [3.9561],
        [3.9130]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 1.1148e-01,  9.9998e-01,  5.6919e-03,  5.9522e+00,  2.1059e+00,
         2.3813e+00, -3.0366e+00,  4.9489e+00,  3.0000e-01])
tensor([[4.0992],
        [4.1000],
        [4.0873]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1033,  1.0000,  0.0057,  0.0844,  1.5375, -0.6881, -3.4439, -0.2534,
        -0.0000])
tensor([[4.1578],
        [4.1683],
        [4.1684]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 1.1048e-01,  9.9998e-01,  5.6919e-03, -2.4822e+00,  1.0418e+00,
        -1.1978

tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-02,  1.5493e-05, -2.8316e-06,
        -1.0351e-09, -5.1023e-08,  1.7245e-06, -0.0000e+00])
tensor([[4.1583],
        [4.1682],
        [4.1678]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-02, -2.2236e-05, -1.8359e-05,
        -1.6781e-09, -4.8996e-07,  2.7187e-07, -0.0000e+00])
tensor([[4.1583],
        [4.1682],
        [4.1678]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-02,  2.7229e-05, -4.8774e-06,
        -1.3832e-09,  4.0665e-07,  3.9045e-07, -0.0000e+00])
tensor([[4.1583],
        [4.1682],
        [4.1678]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-02, -3.5885e-05,  8.8332e-06,
         1.6569e-09,  5.1480e-07, -2.2056e-06, -0.0000e+00])
tensor([[4.1583],
        [4.1682],
        [4.1678]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 2.9122e-06,  9.9987e-01,  1.6127e-02, -3.05

tensor([-1.7681e-01,  9.9987e-01,  1.6127e-02,  5.3411e-01,  4.3539e-01,
        -1.6184e+01, -2.6629e+00,  4.2741e-02, -3.0000e-01])
tensor([[4.1181],
        [4.1443],
        [4.1573]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.1119,   0.9999,   0.0161,   0.4498,   0.1273, -14.8014,  -2.2862,
          0.1411,  -0.3000])
tensor([[4.1287],
        [4.1512],
        [4.1611]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.0484,   0.9999,   0.0161,   0.3158,  -0.1133, -13.6507,  -1.8344,
          0.1570,  -0.3000])
tensor([[4.1276],
        [4.1505],
        [4.1607]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.0143,   0.9999,   0.0161,   0.1364,  -0.3268, -12.8634,  -1.1829,
          0.0419,  -0.3000])
tensor([[4.1432],
        [4.1604],
        [4.1659]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.0785,   0.9999,   0.0161,  -0.1141,  -0.5645, -12.6344,  -0.2144,
         -0.2762,  -0.3000])
tensor([[4.0759],
        

tensor([ -0.2463,   0.9971,  -0.0758,  -0.0900,   0.9943, -17.2461,  -3.3831,
         -2.1445,  -0.3000])
tensor([[4.1158],
        [4.1421],
        [4.1552]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.2363,   0.9971,  -0.0758,   0.7706,   0.4152, -15.9161,  -2.6480,
         -0.5356,  -0.3000])
tensor([[4.1233],
        [4.1468],
        [4.1576]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-2.2093e-01,  9.9712e-01, -7.5825e-02,  7.1355e-01,  2.2936e-03,
        -1.4679e+01, -2.0388e+00, -2.3707e-01, -3.0000e-01])
tensor([[4.1317],
        [4.1520],
        [4.1602]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.2019,   0.9971,  -0.0758,   0.5396,  -0.2104, -13.7293,  -1.5417,
         -0.1578,  -0.3000])
tensor([[4.1361],
        [4.1549],
        [4.1619]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.1798,   0.9971,  -0.0758,   0.3455,  -0.3514, -13.0482,  -1.0636,
         -0.1587,  -0.3000])
tensor([[4.1451],
        

tensor([ -0.4854,   0.7712,  -0.6365,   0.1465,   1.8664, -18.3525,  -5.0052,
         -0.5654,  -0.3000])
tensor([[3.6608],
        [3.8101],
        [3.9299]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.4973,   0.7712,  -0.6365,   0.9969,   0.5373, -16.9199,  -3.1597,
          0.9188,  -0.3000])
tensor([[3.8124],
        [3.9208],
        [4.0051]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([-4.9981e-01,  7.7124e-01, -6.3655e-01,  8.3991e-01,  6.9727e-03,
        -1.5154e+01, -2.5610e+00,  1.1511e+00, -3.0000e-01])
tensor([[3.7951],
        [3.9031],
        [3.9879]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.4958,   0.7712,  -0.6365,   0.5149,  -0.2511, -13.6613,  -1.9960,
          1.0164,  -0.3000])
tensor([[3.7904],
        [3.8963],
        [3.9799]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.4872,   0.7712,  -0.6365,   0.2158,  -0.4043, -12.5890,  -1.4056,
          0.6879,  -0.3000])
tensor([[3.8229],
        

tensor([ 4.0322e-02,  1.3464e-02, -9.9991e-01,  8.4195e-01, -4.7439e-01,
        -1.6085e+01, -8.0175e-01,  2.9801e+00, -3.0000e-01])
tensor([[4.1572],
        [4.1685],
        [4.1693]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 6.5629e-02,  1.3464e-02, -9.9991e-01,  3.3950e-01, -5.7057e-01,
        -1.4434e+01, -3.8468e-01,  2.5432e+00, -3.0000e-01])
tensor([[4.1569],
        [4.1686],
        [4.1697]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.0942,   0.0135,  -0.9999,  -0.0515,  -0.4863, -13.1061,  -0.2398,
          1.9477,  -0.3000])
tensor([[4.1464],
        [4.1570],
        [4.1564]], device='cuda:0')
tensor([[1]], device='cuda:0')
tensor([ 0.1088,  0.0135, -0.9999, -0.3641, -2.0279, -0.8972,  2.7527,  0.9676,
        -0.0000])
tensor([[4.1574],
        [4.1685],
        [4.1690]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.1219,  0.0135, -0.9999, -0.5139,  2.0335, -8.4052, -1.6241,  0.4013,
        -0.3000])
tensor([[4.1556],

tensor([ 4.0243e-01,  1.3464e-02, -9.9991e-01,  1.0009e+00,  1.0623e+00,
         1.6785e+01,  2.6152e-01,  3.8070e+00,  3.0000e-01])
tensor([[4.1498],
        [4.1611],
        [4.1613]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3751,  0.0135, -0.9999,  0.1676,  4.5911, -3.1232, -4.5346,  2.6177,
        -0.3000])
tensor([[4.1570],
        [4.1686],
        [4.1696]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 3.8380e-01,  1.3464e-02, -9.9991e-01,  1.2366e-01,  1.4927e+00,
        -1.3673e+01, -3.3997e+00,  2.9012e+00, -3.0000e-01])
tensor([[3.7753],
        [3.8709],
        [3.9480]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 4.0639e-01,  1.3464e-02, -9.9991e-01, -2.4510e-01, -6.5027e-01,
        -1.3713e+01, -8.2222e-01,  1.7596e+00, -3.0000e-01])
tensor([[3.8763],
        [3.8309],
        [3.7614]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.4155,  0.0135, -0.9999, -0.4286, -3.6348,  0.5235,  3.2140,  0.8536,
        

tensor([ 4.3857e-01,  1.3464e-02, -9.9991e-01, -4.5646e-01, -5.7523e-01,
        -1.3628e+01, -1.0084e+00,  6.3225e-01, -3.0000e-01])
tensor([[3.7007],
        [3.6189],
        [3.5045]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.4641,  0.0135, -0.9999, -0.8172, -4.0077,  2.4827,  3.5417, -0.6519,
         0.3000])
tensor([[3.8082],
        [3.7487],
        [3.6617]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 4.5624e-01,  1.3464e-02, -9.9991e-01, -6.6989e-01, -1.8220e+00,
         1.3526e+01,  3.4081e+00, -7.4900e-01,  3.0000e-01])
tensor([[3.8065],
        [3.7467],
        [3.6593]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 4.3033e-01,  1.3464e-02, -9.9991e-01, -8.8681e-01,  9.3888e-02,
         1.5690e+01,  1.4569e+00, -2.1436e+00,  3.0000e-01])
tensor([[3.9403],
        [3.9082],
        [3.8549]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 3.9295e-01,  1.3464e-02, -9.9991e-01, -1.0169e+00,  1.0029e-01,
         1.7791

tensor([ 0.3193,  0.0135, -0.9999,  1.5285, -0.8646, -0.3283,  1.1123,  3.7295,
        -0.0000])
tensor([[4.1569],
        [4.1687],
        [4.1697]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([  0.3292,   0.0135,  -0.9999,   0.6095,   2.3596, -11.5606,  -2.9025,
          3.7344,  -0.3000])
tensor([[4.1568],
        [4.1686],
        [4.1698]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 3.6219e-01,  1.3464e-02, -9.9991e-01, -6.1499e-01, -2.2889e-01,
        -1.5085e+01, -1.7866e+00,  3.4119e+00, -3.0000e-01])
tensor([[3.9475],
        [3.9168],
        [3.8654]], device='cuda:0')
tensor([[0]], device='cuda:0')
tensor([ 0.3806,  0.0135, -0.9999, -1.4478, -4.1490,  2.4268,  3.7759,  2.3419,
         0.3000])
tensor([[4.1573],
        [4.1685],
        [4.1693]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ 0.3926,  0.0135, -0.9999, -2.0218,  1.9683, -6.8183, -1.8215,  2.1871,
        -0.3000])
tensor([[4.1536],
        [4.1657],
        [4.1669]]

tensor([ -0.6659,  -0.9478,  -0.3189,   1.3438,  -1.0430, -19.3354,   0.9351,
          3.8048,  -0.3000])
tensor([[2.7069],
        [3.0064],
        [3.2690]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.8379,  -0.9478,  -0.3189,   0.7685,  -0.9640, -17.1936,   1.2643,
          3.5797,  -0.3000])
tensor([[0.1147],
        [0.8521],
        [1.5115]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -0.9837,  -0.9478,  -0.3189,   0.2174,  -0.6517, -15.6027,   1.1214,
          2.8287,  -0.3000])
tensor([[-1.2986],
        [-0.5760],
        [ 0.1831]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -1.1091,  -0.9478,  -0.3189,  -0.1306,  -0.3976, -14.2684,   0.9832,
          2.2481,  -0.3000])
tensor([[-4.5053],
        [-3.9036],
        [-3.0535]], device='cuda:0')
tensor([[2]], device='cuda:0')
tensor([ -1.2189,  -0.9478,  -0.3189,  -0.3448,  -0.1425, -13.1119,   0.6824,
          1.6163,  -0.3000])
tensor([[-6.3300],
        [-5.7214],
        [